PACKING_VARIANTS := "" "_SPINOR"

#
# Common supporting targets
#

# Find the latest firmware from rkbin
# $1: base dir
# $2: filter
define find_latest_file
$(shell find $(1) -name "$(2)" 2>/dev/null | sort -V | tail -n 1 | xargs realpath)
endef

# Pack U-Boot
# $1: SoC
# $2: Variant
define pack_uboot
	if [ -f "rkbin/RKBOOT/$(subst rk,RK,$(1))MINIALL$(2).ini" ]; then \
		sed -i "s|^FlashBoot=.*|FlashBoot=../src/spl/u-boot-spl.bin|g" "rkbin/RKBOOT/$(subst rk,RK,$(1))MINIALL$(2).ini"; \
		sed -i "s|^PATH=.*|PATH=rkboot$(2).bin|g" "rkbin/RKBOOT/$(subst rk,RK,$(1))MINIALL$(2).ini"; \
		sed -i "s|^IDB_PATH=.*|IDB_PATH=idblock$(2).img|g" "rkbin/RKBOOT/$(subst rk,RK,$(1))MINIALL$(2).ini"; \
		cd rkbin && tools/boot_merger "RKBOOT/$(subst rk,RK,$(1))MINIALL$(2).ini" && cd ..; \
	fi;
endef

# Build and Pack U-Boot
# $1: SoC
define build_uboot
	$(UMAKE) BL31=$(call find_latest_file,rkbin/bin,"$(1)_bl31_v*.elf") all u-boot.itb
	$(foreach variant,$(PACKING_VARIANTS),$(call pack_uboot,$(1),$(variant)))
endef

# Install U-Boot binaries
define install_uboot
	mkdir -p out/$@
	mv rkbin/rkboot*.bin rkbin/idblock*.img "out/$@"
	mv src/u-boot.itb "out/$@/"
	cp setup/u-boot_setup-rockchip.sh out/$@/setup.sh
	cp setup/u-boot_setup-rockchip.ps1 out/$@/setup.ps1
endef

# Define standard U-Boot targets
# $1: product ID
# $2: product SoC
# $3: product defconfig
define uboot_targets

UBOOT_PRODUCTS += $(1)

.PHONY: $(1)_defconfig
$(1)_defconfig: clean_config
	$$(UMAKE) $(3)

.PHONY: $(1)_build
$(1)_build: $(1)_defconfig
	$$(call build_uboot,$(2))

.PHONY: $(1)
$(1): $(1)_build
	$$(call install_uboot)

endef

#
# Device build targets
#

$(eval $(call uboot_targets,radxa-rcore-rk3308-io,rk3308,radxa-rcore-rk3308-io_defconfig))
$(eval $(call uboot_targets,rock-pi-s,rk3308,rock-pi-s-rk3308_defconfig))
$(eval $(call uboot_targets,rock-s0,rk3308,rock-s0-rk3308_defconfig))

$(eval $(call uboot_targets,radxa-rk3528,rk3528,rock-2-rk3528_defconfig))

$(eval $(call uboot_targets,radxa-cm3-io,rk3566,radxa-cm3-io-rk3566_defconfig))
$(eval $(call uboot_targets,radxa-cm3-rpi-cm4-io,rk3566,radxa-cm3-rpi-cm4-io-rk3566_defconfig))
$(eval $(call uboot_targets,rock-3c,rk3566,rock-3c-rk3566_defconfig))

$(eval $(call uboot_targets,radxa-cm3i-io,rk3568,radxa-cm3i-io-rk3568_defconfig))
$(eval $(call uboot_targets,radxa-cm3j-rpi-cm4-io,rk3568,radxa-cm3j-rpi-cm4-io-rk3568_defconfig))
$(eval $(call uboot_targets,rock-3a,rk3568,rock-3a-rk3568_defconfig))
$(eval $(call uboot_targets,rock-3b,rk3568,rock-3b-rk3568_defconfig))

$(eval $(call uboot_targets,radxa-rk3576,rk3576,rock-4d-rk3576_defconfig))
$(eval $(call uboot_targets,radxa-rk3576-spi,rk3576,rock-4d-spi-rk3576_defconfig))

$(eval $(call uboot_targets,radxa-e54c,rk3588,radxa-e54c-rk3588s_defconfig))
$(eval $(call uboot_targets,radxa-e54c-spi,rk3588,radxa-e54c-spi-rk3588s_defconfig))
$(eval $(call uboot_targets,rock-5b-plus,rk3588,rock-5b-plus-rk3588_defconfig))
$(eval $(call uboot_targets,rock-5c,rk3588,rock-5c-rk3588s_defconfig))
$(eval $(call uboot_targets,rock-5c-spi,rk3588,rock-5c-spi-rk3588s_defconfig))
